# Data Cleaning

In [136]:
# Read in the customer data file using Python in Jupyter Notebook
import numpy as np
import pandas as pd
# Start by importing numpy and pandas

In [254]:
df1 = pd.read_csv(input(''))
df1
# To load the data as a DataFrame will use the above code
# Asking the user to input the file name for the file to be processed
# Assign to a variable to save it into a dataframe
# The data is in an awkward format will need to separate customer records into columns

 customer_list_updated.csv

       cust_id|date|time|name|email|phone|sms-opt-out
0    1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1    2|2023-05-22|12:30:45|R&! Geller|rossg@central...
2    3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3    4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4    5|2023-11-18|14:22:10|Joey|howyoudoing@central...
..                                                 ...
516  517|2024-02-15|11:30:30|Perry the Platypus|age...
517  518|2024-05-01|15:55:45|Baljeet|baljeet@danvil...
518  519|2023-03-05|09:20:00|Buford|buford@danville...
519  520|2023-05-18|13:45:15|Vanessa D.^|vanessa@da...
520  521|2023-08-01|18:10:30|Linda Flynn-Fletcher|l...

[521 rows x 1 columns]

In [256]:
df1 = pd.read_csv(input(''), sep = '|')
df1
# In order to separate the customer recordsinto columns I used the separator parameter to display the values without the pipe symbol 
# Each record is then separated where the pipe symbol is located and separated into their perspective columns
# Now, if I do it this way, I can make it easier to preview the data
# call on the variable to display

 customer_list_updated.csv

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R&! Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N
...,...,...,...,...,...,...,...
516,517,2024-02-15,11:30:30,Perry the Platypus,agentp@danvillekids.com,555-555-3206,N
517,518,2024-05-01,15:55:45,Baljeet,baljeet@danvillekids.com,555-555-3207,N
518,519,2023-03-05,09:20:00,Buford,buford@danvillekids.com,555-555-3208,N
519,520,2023-05-18,13:45:15,Vanessa D.^,vanessa@danvillekids.com,555-555-3209,N
520,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N

In [257]:
df1.info()
# checking the structure after having separated the customer records into columns using the info attribute 
# This will show the summary infromation about df1 to help me identify any irregularities in the columns
# Here I can tell I have 521 records
# I can tell have a total of 7 columns
# The Dtype for most of this data is string except for the customer id which an integer of 64 bytes
# The amount of non-null values or any value that is not none is 521 entries compared to 520 non null values in the message opt out column where there could be a missing value and 520 phone non null values in phone which means there could be a missing phone number int hat column
# I will then need to check the contents

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cust_id       521 non-null    int64
 1   date          521 non-null    object
 2   time          521 non-null    object
 3   name          521 non-null    object
 4   email         521 non-null    object
 5   phone         520 non-null    object
 6   sms-opt-out   520 non-null    object
dtypes: int64(1), object(6)
memory usage: 28.6+ KB

In [258]:
df1.head(51)
# looking at the first 50 records with .head() attribute. With this, I'm able to see that the name values have stray characters
# Will need to take out the caret symbol(^) also the (&!) symbols
# Format the phone numbers correctly 
# Decide what to do with the missing valyes in the message opt out column

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R&! Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N
5,6,2024-01-05,10:55:49,P&! Buffay,smellycat@centralperk.coffee,212-555-1006,N
6,7,2024-02-14,16:40:05,Gunther,gunther@centralperk.coffee,212-555-1007,N
7,8,2023-04-20,09:15:30,Janice,ohmygod@centralperk.coffee,212-555-1008,N
8,9,2023-06-30,13:50:55,Mike H.^,mike@centralperk.coffee,212-555-1009,N
9,10,2023-08-25,17:25:10,Emily,emily@centralperk.coffee,212-555-1010,N
10,11,2023-04-12,09:20:30,Walter White,heisenberg@lospolloshermanos.biz,505-555-2001,N
11,12,2023-06-25,13:45:50,Jesse Pinkman,jesse@lospolloshermanos.biz,505-555-2002,N
12,13,2023-08-03,17:30:15,Skyler W.^,skyler@lospolloshermanos.biz,505-555-2003,Y
13,14,2023-10-19,20:05:40,Saul Goodman,bettercallsaul@lospolloshermanos.biz,505-555-2004,N
14,15,2024-02-28,11:15:25,H&! Schrader,hank@lospolloshermanos.biz,505-555-2005,N
15,16,2024-03-10,15:50:35,Gus Fring,gus@lospolloshermanos.biz,505-555-2006,N
16,17,2024-04-22,19:25:50,Mike E.^,mike@lospolloshermanos.biz,505-555-2007,N
17,18,2023-05-14,10:30:45,Marie S.^,marie@lospolloshermanos.biz,505-555-2008,N
18,19,2023-07-27,14:05:00,Todd,todd@lospolloshermanos.biz,505-555-2009,N
19,20,2023-09-09,18:40:15,Lydia R.^,lydia@lospolloshermanos.biz,505-555-2010,N
20,21,2023-01-05,06:15:20,Jon Snow,knowsnothing@westeros.kingdom,123-555-3001,N
21,22,2023-02-18,10:40:35,Daenerys T.^,dragonqueen@westeros.kingdom,123-555-3002,N
22,23,2023-04-22,14:05:50,Tyrion L.^,theimp@westeros.kingdom,123-555-3003,Y
23,24,2023-06-30,18:30:10,Arya Stark,noface@westeros.kingdom,123-555-3004,N
24,25,2023-08-15,22:55:25,Sansa S.^,queenofthenorth@westeros.kingdom,123-555-3005,N
25,26,2023-10-28,07:20:40,Cersei L.^,queenregent@westeros.kingdom,123-555-3006,N
26,27,2023-12-12,11:45:55,J&! Lannister,kingslayer@westeros.kingdom,123-555-3007,N
27,28,2023-03-03,08:10:15,Bran Stark,threeeyedraven@westeros.kingdom,123-555-3008,N
28,29,2023-05-17,12:35:30,Samwell T.^,maester@westeros.kingdom,123-555-3009,N
29,30,2023-07-29,16:00:45,Brienne,brienne@westeros.kingdom,123-555-3010,N
30,31,2023-03-10,09:25:30,Homer S.^,donuts@springfield.power,636-555-4001,N
31,32,2023-05-05,13:50:45,Marge,marge@springfield.power,636-555-4002,N
32,33,2023-07-20,18:15:00,Bart,elbarto@springfield.power,636-555-4003,N
33,34,2023-09-15,22:40:15,Lisa S.^,saxgirl@springfield.power,636-555-4004,Y
34,35,2023-11-08,07:05:30,Maggie,maggie@springfield.power,636-555-4005,N
35,36,2024-01-25,11:30:45,Ned Flanders,ned@springfield.power,636-555-4006,N
36,37,2024-03-18,15:55:00,Mr&! Burns,monty@springfield.power,636-555-4007,N
37,38,2023-04-22,10:20:15,Krusty,krusty@springfield.power,636-555-4008,N
38,39,2023-06-14,14:45:30,Chief Wiggum,wiggum@springfield.power,636-555-4009,N
39,40,2023-08-27,19:10:45,Milhouse,milhouse@springfield.power,636-555-4010,N
40,41,2023-02-12,08:35:15,Michael Scott,mscott@dundermifflin.com,570-555-5001,N
41,42,2023-04-28,12:00:30,Jim H.^,jim@dundermifflin.com,570-555-5002,N
42,43,2023-07-05,16:25:45,Pam Beesly,pam@dundermifflin.com,570-555-5003,Y
43,44,2023-09-22,20:50:00,Dwight Schrute,dwight@dundermifflin.com,570-555-5004,N
44,45,2023-11-30,06:15:15,Angela M.^,angela@dundermifflin.com,570-555-5005,N
45,46,2024-02-14,10:40:30,Kevin M.^,kevin@dundermifflin.com,570-555-5006,N
46,47,2024-04-01,15:05:45,Stanley H.^,stanley@dundermifflin.com,570-555-5007,N
47,48,2023-03-18,09:30:00,Andy B.^,andy@dundermifflin.com,570-555-5008,N
48,49,2023-05-25,13:55:15,Oscar M.^,oscar@dundermifflin.com,570-555-5009,N
49,50,2023-08-10,18:20:30,Creed,creed@dundermifflin.com,570-555-5010,N
50,51,2023-03-22,07:15:20,Eleven,eleven@hawkins.ind,219-555-6001,N

In [259]:
df1["name"] = df1["name"].str.replace("^","")
df1
# I replaced the caret symbol (^) first by pulling the name column in brackets, this will specify the column I want to make changes to 
# I then applied the .str method to make sure the output we get in return is also a string, along with the. replace method to replace the caret symbol with nothing since its at the very end of the name string.
# I then went ahead and assigned it to the same dataframe and same column to save the changes
# Finally I called on it to view the output

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R&! Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N
...,...,...,...,...,...,...,...
516,517,2024-02-15,11:30:30,Perry the Platypus,agentp@danvillekids.com,555-555-3206,N
517,518,2024-05-01,15:55:45,Baljeet,baljeet@danvillekids.com,555-555-3207,N
518,519,2023-03-05,09:20:00,Buford,buford@danvillekids.com,555-555-3208,N
519,520,2023-05-18,13:45:15,Vanessa D.,vanessa@danvillekids.com,555-555-3209,N
520,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N

In [260]:
df1["name"] = df1["name"].str.replace("&!",".")
df1
# I then replaced the (&) and (!) symbol together since I seen that both of them are together for the first 50 records. 
# This time I replaced it with a period since I noticed they were in between a first intial followed by a last name
# I again pulled up the name column in brackets, this will specify the column I want to make changes to
# I then applied the .str method again to make sure the output we get in return is also a string, along with the. replace method
# I then went ahead and assigned it to the same dataframe and same column to save the changes
# Finally, I called on it to view the output

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R. Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N
...,...,...,...,...,...,...,...
516,517,2024-02-15,11:30:30,Perry the Platypus,agentp@danvillekids.com,555-555-3206,N
517,518,2024-05-01,15:55:45,Baljeet,baljeet@danvillekids.com,555-555-3207,N
518,519,2023-03-05,09:20:00,Buford,buford@danvillekids.com,555-555-3208,N
519,520,2023-05-18,13:45:15,Vanessa D.,vanessa@danvillekids.com,555-555-3209,N
520,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N

In [261]:
df1.head(289)

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R. Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N
...,...,...,...,...,...,...,...
284,285,2024-03-15,12:10:30,Pirate Jenny,jenny@keenecounty.police,918-555-2110,N
285,286,2023-01-01,08:00:00,Jean-Luc Picard,picard@enterprise.starfleet,1701-555-2201,N
286,287,2023-02-14,12:25:15,William Riker,riker@enterprise.starfleet,1701-555-2202,N
287,288,2023-03-27,15:50:30,Data,data@enterprise.starfleet,1701-555-2203,N
288,289,2023-05-10,19:15:45,Geordi La Forge,geordi@enterprise.starfleet,1701-555-2204,N